service: appguard-on-lambda-python

frameworkVersion: '3'

plugins:
  - serverless-latest-layer-version
  - serverless-python-requirements

provider:
  name: aws
  logRetentionInDays: 7
  layers:
    - arn:aws:lambda:us-east-1:201476247173:layer:Extrinsec-Appguard:9

functions:
  python:
    handler: main.demo_python
    runtime: python3.9
    environment:
      ES_POLICY_GROUP_NAME: ${env:ES_POLICY_GROUP_NAME, 'observeAll.ability'}
      ES_LICENSE_KEY: '${env:ES_LICENSE_KEY}'
      AWS_LAMBDA_EXEC_WRAPPER: '/opt/extrinsec-appguard.sh'
    events:
      - httpApi:
          path: /python-demo
          method: get
