service: appdefender-on-lambda-nodejs

frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1
  logRetentionInDays: 7
  layers:
    - arn:aws:lambda:us-east-1:201476247173:layer:Extrinsec-Appdefender:1

functions:
  nodejs:
    handler: index.demo_nodejs
    runtime: nodejs16.x
    environment:
      ES_POLICY_GROUP_NAME: ${env:ES_POLICY_GROUP_NAME, 'observeAll.ability'}
      ES_LICENSE_KEY: '${env:ES_LICENSE_KEY}'
      AWS_LAMBDA_EXEC_WRAPPER: '/opt/extrinsec-appdefender.sh'
    events:
      - httpApi:
          path: /nodejs-demo
          method: get
